[package]
name = "toy_payment_prc"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.22"
rust_decimal_macros = "1.22"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
